# Generated by Django 3.2 on 2021-08-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210807_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=999.99, max_digits=6),
        ),
    ]
