# Generated by Django 3.2 on 2021-08-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_price_per_night'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelroomtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['price_per_night']},
        ),
        migrations.RemoveField(
            model_name='hotelroomtype',
            name='price_per_night',
        ),
    ]
